"""add account identities

Revision ID: 3d7bb3981d70
Revises: db788447d61e
Create Date: 2026-08-23 23:28:03.815514

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "3d7bb3981d70"
down_revision: Union[str, Sequence[str], None] = "db788447d61e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    auth_provider = postgresql.ENUM("GOOGLE", name="auth_provider")
    auth_provider.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "account_identities",
        sa.Column("provider_user_id", sa.String(length=255), nullable=False),
    )
    op.alter_column(
        "account_identities",
        "provider",
        existing_type=sa.VARCHAR(length=50),
        type_=auth_provider,
        postgresql_using="upper(provider)::auth_provider",
        existing_nullable=False,
    )
    op.drop_constraint(
        op.f("uq_account_identity_provider_subject"),
        "account_identities",
        type_="unique",
    )
    op.create_unique_constraint(
        "uq_provider_user", "account_identities", ["provider", "provider_user_id"]
    )
    op.drop_column("account_identities", "provider_subject")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "account_identities",
        sa.Column(
            "provider_subject",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint("uq_provider_user", "account_identities", type_="unique")
    op.create_unique_constraint(
        op.f("uq_account_identity_provider_subject"),
        "account_identities",
        ["provider", "provider_subject"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "account_identities",
        "provider",
        existing_type=postgresql.ENUM("GOOGLE", name="auth_provider"),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
    )
    op.drop_column("account_identities", "provider_user_id")
    postgresql.ENUM("GOOGLE", name="auth_provider").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
